# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений (работает)
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления (работает)
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token c73a132e29fd07d5585ea65fe3e33c01ddf93bbf

{
  "title": "Окна",
  "description": "переходи на птиц",
  "status": "OPEN"
}

###

# попытка поменять объявление (работает)
PATCH {{baseUrl}}/advertisements/7/
Content-Type: application/json
Authorization: Token c73a132e29fd07d5585ea65fe3e33c01ddf93bbf

{
  "description": "Just do it!",
  "status": "OPEN"
}

###

# фильтрация по создателю (работает)
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате (работает)
GET {{baseUrl}}/advertisements/?created_at_after=2022-09-12
Content-Type: application/json

# root 307b789b8558cec088986ad3ea42cf701725219e
# root2 c73a132e29fd07d5585ea65fe3e33c01ddf93bbf

###

# delete advertisement works
DELETE {{baseUrl}}/advertisements/7/
Content-Type: application/json
Authorization: Token c73a132e29fd07d5585ea65fe3e33c01ddf93bbf