# Generated by Django 4.0.6 on 2022-08-31 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='measurement', serialize=False, to='measurement.sensor')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='температура')),
                ('date', models.DateField(auto_now=True, verbose_name='дата измерения')),
            ],
        ),
    ]
