# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api/

# получение датчиков
GET {{baseUrl}}sensor/
Content-Type: application/json

###

# получение датчика
GET {{baseUrl}}sensor/1
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}sensor/
Content-Type: application/json

{
  "name": "GTR-500",
  "location": "гараж"
}

###

# обновление датчика
PATCH {{baseUrl}}sensor/2/
Content-Type: application/json

{
  "name": "TRS-10000",
  "location": "бассейн"
}

###

# список всех измерений
GET {{baseUrl}}measurements/
Content-Type: application/json

###

# создать измерение
POST {{baseUrl}}measurement/1/
Content-Type: application/json

{
  "sensor": "4",
  "temperature": "10.05"
}

